package com.arogyalens.history;

import com.arogyalens.dto.AnalysisResponse;
import com.arogyalens.exception.ArogyaLensException;
import com.arogyalens.privacy.PrivacyService;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.regex.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Opt-in "My history". The browser sends an anonymous {@code X-Device-Id} only when the user turns
 * history on; everything is PII-masked again before it is stored, and users can delete one item or
 * everything. Recording never fails the user's request.
 */
@Service
public class HistoryService {

    private static final Logger LOG = LoggerFactory.getLogger(HistoryService.class);
    private static final Pattern DEVICE_ID = Pattern.compile("^[A-Za-z0-9-]{16,64}$");
    private static final int MAX_SUMMARY = 4000;
    private static final int MAX_TITLE = 200;

    private final HistoryRepository repository;
    private final PrivacyService privacyService;
    private final boolean enabled;
    private final int maxEntries;
    private final Clock clock;

    public HistoryService(
            HistoryRepository repository,
            PrivacyService privacyService,
            @Value("${arogyalens.history.enabled:true}") boolean enabled,
            @Value("${arogyalens.history.max-entries-per-device:50}") int maxEntries) {
        this.repository = repository;
        this.privacyService = privacyService;
        this.enabled = enabled;
        this.maxEntries = Math.max(1, maxEntries);
        this.clock = Clock.systemUTC();
    }

    /** Public view of a stored entry. */
    public record HistoryItem(
            Long id,
            String kind,
            String title,
            String summary,
            String language,
            Instant createdAt) {
        static HistoryItem of(HistoryEntry e) {
            return new HistoryItem(
                    e.getId(),
                    e.getKind().name(),
                    e.getTitle(),
                    e.getSummary(),
                    e.getLanguage(),
                    e.getCreatedAt());
        }
    }

    /** Whether history storage is switched on for this deployment. */
    public boolean isEnabled() {
        return enabled;
    }

    /** True when the value looks like an anonymous device id generated by the frontend. */
    public static boolean isValidDeviceId(String deviceId) {
        return deviceId != null && DEVICE_ID.matcher(deviceId).matches();
    }

    /** Stores a masked summary of a scan if the client opted in. */
    public void recordScan(String deviceId, AnalysisResponse analysis, String language) {
        if (!shouldRecord(deviceId) || analysis == null) {
            return;
        }
        String title = analysis.documentLabel() != null ? analysis.documentLabel() : "Scan";
        String summary = analysis.familySummary();
        if (summary == null || summary.isBlank()) {
            var d = analysis.dashboard();
            summary =
                    d == null
                            ? "Analysis completed."
                            : "%d values found: %d within range, %d to discuss, %d need attention."
                                    .formatted(
                                            d.total(),
                                            d.withinRange(),
                                            d.needsDiscussion(),
                                            d.importantAttention());
        }
        save(deviceId, HistoryEntry.Kind.SCAN, title, summary, language);
    }

    /** Stores a masked question and answer if the client opted in. */
    public void recordChat(String deviceId, String question, String answer, String language) {
        if (!shouldRecord(deviceId) || question == null || answer == null) {
            return;
        }
        save(deviceId, HistoryEntry.Kind.CHAT, question, answer, language);
    }

    /** Lists the newest entries for a device. */
    @Transactional(readOnly = true)
    public List<HistoryItem> list(String deviceId) {
        requireDevice(deviceId);
        return repository
                .findByDeviceIdOrderByCreatedAtDescIdDesc(deviceId, PageRequest.of(0, maxEntries))
                .stream()
                .map(HistoryItem::of)
                .toList();
    }

    /** Deletes one entry; returns 404 when it does not belong to the device. */
    public void delete(String deviceId, long id) {
        requireDevice(deviceId);
        if (repository.deleteByIdAndDeviceId(id, deviceId) == 0) {
            throw new ArogyaLensException(
                    "HISTORY_NOT_FOUND",
                    "History item not found",
                    "That history item no longer exists.",
                    HttpStatus.NOT_FOUND);
        }
    }

    /** Deletes every entry for the device and returns how many were removed. */
    public long deleteAll(String deviceId) {
        requireDevice(deviceId);
        return repository.deleteByDeviceId(deviceId);
    }

    private boolean shouldRecord(String deviceId) {
        return enabled && isValidDeviceId(deviceId);
    }

    private void requireDevice(String deviceId) {
        if (!enabled) {
            throw new ArogyaLensException(
                    "HISTORY_DISABLED",
                    "History disabled",
                    "History is turned off on this server.",
                    HttpStatus.NOT_FOUND);
        }
        if (!isValidDeviceId(deviceId)) {
            throw new ArogyaLensException(
                    "DEVICE_ID_REQUIRED",
                    "Missing or invalid X-Device-Id",
                    "Turn on history to use this feature.",
                    HttpStatus.BAD_REQUEST);
        }
    }

    private void save(
            String deviceId,
            HistoryEntry.Kind kind,
            String title,
            String summary,
            String language) {
        try {
            repository.save(
                    new HistoryEntry(
                            deviceId,
                            kind,
                            truncate(mask(title), MAX_TITLE),
                            truncate(mask(summary), MAX_SUMMARY),
                            language == null || language.isBlank() ? "en" : truncate(language, 8),
                            Instant.now(clock)));
            prune(deviceId);
        } catch (RuntimeException ex) {
            LOG.warn("History write skipped: {}", ex.getClass().getSimpleName());
        }
    }

    private void prune(String deviceId) {
        List<HistoryEntry> overflow =
                repository.findByDeviceIdOrderByCreatedAtDescIdDesc(
                        deviceId, PageRequest.of(1, maxEntries));
        if (!overflow.isEmpty()) {
            repository.deleteAll(overflow);
        }
    }

    private String mask(String text) {
        return privacyService.scanAndRedact(text).redactedText();
    }

    private static String truncate(String s, int max) {
        String v = s.strip();
        return v.length() <= max ? v : v.substring(0, max - 1) + "…";
    }
}
