package com.arogyalens.controller;

import com.arogyalens.ai.GeminiService;
import com.arogyalens.dto.ChatRequest;
import com.arogyalens.dto.ChatResponse;
import com.arogyalens.dto.TtsRequest;
import com.arogyalens.dto.VoiceQueryRequest;
import com.arogyalens.dto.VoiceQueryResponse;
import com.arogyalens.service.VoiceService;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/** Ask-anything assistant, chat and Gemini text-to-speech fallback. */
@RestController
@RequestMapping("/api")
public class VoiceController {

    private final VoiceService voiceService;
    private final GeminiService geminiService;

    public VoiceController(VoiceService voiceService, GeminiService geminiService) {
        this.voiceService = voiceService;
        this.geminiService = geminiService;
    }

    @PostMapping("/voice/query")
    public VoiceQueryResponse voice(@Valid @RequestBody VoiceQueryRequest request) {
        return voiceService.query(request);
    }

    @PostMapping("/chat")
    public ChatResponse chat(@Valid @RequestBody ChatRequest request) {
        return voiceService.chat(request);
    }

    /** Returns WAV audio generated by Gemini TTS (used when the browser lacks a voice for the language). */
    @PostMapping(value = "/voice/tts", produces = "audio/wav")
    public ResponseEntity<byte[]> tts(@Valid @RequestBody TtsRequest request) {
        byte[] wav = geminiService.synthesizeSpeech(request.text());
        return ResponseEntity.ok().contentType(MediaType.parseMediaType("audio/wav")).body(wav);
    }
}
