package com.arogyalens.controller;

import com.arogyalens.ai.GeminiService;
import com.arogyalens.dto.ChatRequest;
import com.arogyalens.dto.ChatResponse;
import com.arogyalens.dto.TtsRequest;
import com.arogyalens.dto.VoiceQueryRequest;
import com.arogyalens.dto.VoiceQueryResponse;
import com.arogyalens.history.HistoryController;
import com.arogyalens.history.HistoryService;
import com.arogyalens.service.VoiceService;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/** Ask-anything assistant, chat and Gemini text-to-speech fallback. */
@RestController
@RequestMapping("/api")
public class VoiceController {

    private final VoiceService voiceService;
    private final GeminiService geminiService;
    private final HistoryService historyService;

    public VoiceController(
            VoiceService voiceService, GeminiService geminiService, HistoryService historyService) {
        this.voiceService = voiceService;
        this.geminiService = geminiService;
        this.historyService = historyService;
    }

    @PostMapping("/voice/query")
    public VoiceQueryResponse voice(
            @Valid @RequestBody VoiceQueryRequest request,
            @RequestHeader(value = HistoryController.DEVICE_HEADER, required = false)
                    String deviceId) {
        VoiceQueryResponse response = voiceService.query(request);
        historyService.recordChat(
                deviceId, request.query(), response.answer(), response.language());
        return response;
    }

    @PostMapping("/chat")
    public ChatResponse chat(
            @Valid @RequestBody ChatRequest request,
            @RequestHeader(value = HistoryController.DEVICE_HEADER, required = false)
                    String deviceId) {
        ChatResponse response = voiceService.chat(request);
        historyService.recordChat(
                deviceId, request.message(), response.answer(), request.language());
        return response;
    }

    /**
     * Returns WAV audio generated by Gemini TTS (used when the browser lacks a voice for the
     * language).
     */
    @PostMapping(value = "/voice/tts", produces = "audio/wav")
    public ResponseEntity<byte[]> tts(@Valid @RequestBody TtsRequest request) {
        byte[] wav = geminiService.synthesizeSpeech(request.text());
        return ResponseEntity.ok().contentType(MediaType.parseMediaType("audio/wav")).body(wav);
    }
}
