-- PII-masked scan and chat history, keyed by an anonymous per-device id.
CREATE TABLE history_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   VARCHAR(64)   NOT NULL,
    kind        VARCHAR(16)   NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    summary     VARCHAR(4000) NOT NULL,
    language    VARCHAR(8)    NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_history_device_created ON history_entry (device_id, created_at DESC);
